# Generated by Django 5.2.17 on 2026-09-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0013_alter_item_script_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="extra_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Type-specific metadata (e.g. Business Rule active/abort_action, Scheduled Job run schedule) - see sn_schema.SCRIPT_TYPE_SCHEMAS.",
            ),
        ),
    ]
