# Generated by Django 5.2.17 on 2026-09-15 11:38

import django.db.models.deletion
import lottery.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrizeTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("special", "special"),
                            ("first", "first"),
                            ("second", "second"),
                            ("third", "third"),
                            ("fourth", "fourth"),
                            ("fifth", "fifth"),
                            ("sixth", "sixth"),
                            ("seventh", "seventh"),
                            ("eighth", "eighth"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="e.g. Giải đặc biệt", max_length=40),
                ),
                (
                    "payout_amount",
                    models.BigIntegerField(
                        help_text="VND paid per winning number, per 10,000đ ticket."
                    ),
                ),
                (
                    "count_per_draw",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="How many winning numbers this tier draws per station per day (display only).",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LotteryResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw_date", models.DateField()),
                ("station", models.CharField(max_length=60)),
                ("special", models.CharField(blank=True, max_length=20)),
                ("first", models.CharField(blank=True, max_length=20)),
                ("second", models.CharField(blank=True, max_length=20)),
                ("third", models.CharField(blank=True, max_length=60)),
                ("fourth", models.CharField(blank=True, max_length=120)),
                ("fifth", models.CharField(blank=True, max_length=20)),
                ("sixth", models.CharField(blank=True, max_length=60)),
                ("seventh", models.CharField(blank=True, max_length=20)),
                ("eighth", models.CharField(blank=True, max_length=20)),
                (
                    "source",
                    models.CharField(
                        choices=[("sync", "Daily sync"), ("live", "Live lookup")],
                        default="sync",
                        max_length=10,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-draw_date", "station"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("draw_date", "station"),
                        name="unique_lottery_result_per_station_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("number", models.CharField(max_length=6)),
                ("station", models.CharField(max_length=60)),
                (
                    "draw_date",
                    models.DateField(default=lottery.models.default_draw_date),
                ),
                ("cost", models.PositiveIntegerField(default=10000)),
                ("matched_number", models.CharField(blank=True, max_length=20)),
                ("payout_amount", models.BigIntegerField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="lottery.prizetier",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lottery_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-draw_date", "-created_at"],
            },
        ),
    ]
